# Generated by Django 5.2.7 on 2025-10-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=99)),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
