# Generated by Django 5.2.7 on 2025-10-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
