# Generated by Django 4.2.25 on 2025-11-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('GLC', 'Global countries'), ('NWS', 'Global news'), ('NO', 'Not in list')], default='NO', max_length=5)),
            ],
        ),
    ]
